#!/bin/sh -e


undo=
if [ "$1" = "-u" ]; then
	undo="Un"
	shift
fi


base="$1"
name="$2"

bases_dir=$HOME/store/chroots/
err() {
	echo "$1" >&2
	echo "Must be one of:" $(find "$bases_dir" -mindepth 1 -maxdepth 1 -type d | sed "s:$bases_dir::g") >&2
	exit 1
}

basedir="${bases_dir}${base}"
[ -z "${base}"    ] && err "No base!"
[ -d "${basedir}" ] || err "Unknown base!"

if [ -z "${name}" ]; then
	echo "No name!" >&2
	exit 1
fi
builddir="${base}-${name}/"
upperdir=".prep-buildd--${builddir}/"


echo "${undo}Preparing ${builddir}..."


if [ -z "${undo}" ]; then
	mkdir "${builddir}" "${upperdir}"
	sudo mount -t tmpfs "buildd-${base}" "${upperdir}"
	mkdir "${upperdir}up" "${upperdir}work"

	sudo mount -t overlay overlay -o "lowerdir=${basedir},upperdir=${upperdir}up,workdir=${upperdir}work" "${builddir}"
	sudo mount --bind /proc "${builddir}proc"

	sudo sh -c "echo ${base} ${name} > ${builddir}etc/debian_chroot"
	echo export TERM=xterm-256color
	echo unset LANGUAGE LANG
	echo 'PATH=/usr/bin:/usr/sbin:$PATH'
else
	sudo umount "${builddir}proc" "${builddir}" "${upperdir}"
	rmdir "${builddir}" "${upperdir}"
fi
