#!/bin/bash


source "${0%\/[^\/]*}/rrd_graph_config.sh"


function generate_cpu_graph {
	period="$1"
	start="$2"
	cpu_num="$3"

	generate_graph                                                           \
		"$image_dir/cpu-$cpu_num-$period.png"                                  \
		--start "$start"                                                       \
		--title "\"CPU $cpu_num usage - by $period\""                          \
		--slope-mode                                                           \
		--upper-limit 100                                                      \
		--lower-limit 0                                                        \
		--rigid                                                                \
		--vertical-label Percent                                               \
		"DEF:idle=$data_dir/cpu-$cpu_num/cpu-idle.rrd:value:AVERAGE"           \
		"DEF:nice=$data_dir/cpu-$cpu_num/cpu-nice.rrd:value:AVERAGE"           \
		"DEF:user=$data_dir/cpu-$cpu_num/cpu-user.rrd:value:AVERAGE"           \
		"DEF:waitio=$data_dir/cpu-$cpu_num/cpu-wait.rrd:value:AVERAGE"         \
		"DEF:system=$data_dir/cpu-$cpu_num/cpu-system.rrd:value:AVERAGE"       \
		"DEF:softirq=$data_dir/cpu-$cpu_num/cpu-softirq.rrd:value:AVERAGE"     \
		"DEF:interrupt=$data_dir/cpu-$cpu_num/cpu-interrupt.rrd:value:AVERAGE" \
		"DEF:steal=$data_dir/cpu-$cpu_num/cpu-steal.rrd:value:AVERAGE"         \
		"AREA:steal$color_cpu_steal:\"Steal\""                                 \
		"AREA:system$color_cpu_system:\"System\":STACK"                        \
		"AREA:waitio$color_cpu_waitio:\"Wait-IO\":STACK"                       \
		"AREA:nice$color_cpu_nice:\"Nice\":STACK"                              \
		"AREA:user$color_cpu_user:\"User\":STACK"                              \
		"AREA:softirq$color_cpu_softirq:\"Soft-IRQ\c\":STACK"                  \
		"AREA:interrupt$color_cpu_irq:\"IRQ\":STACK"                           \
		"AREA:idle$color_cpu_idle:\"Idle\\c\":STACK"                           \
		"COMMENT:\"$last_update\""
}


color_cpu_idle='#e7e7e7'
color_cpu_nice='#00df00'
color_cpu_user='#0000fd'
color_cpu_waitio='#fdaf00'
color_cpu_system='#fd0000'
color_cpu_softirq='#fd00fd'
color_cpu_irq='#9f009f'
color_cpu_steal='#000000'


each_period generate_cpu_graph 0
