#!/bin/sh

cd /usr/local/etc/dnsmasq/adblock
setpriv --reuid=shared-config --regid="$(id -gn shared-config)" --init-groups ./generate || exit
#systemctl reload dnsmasq

sudo -iu shared-config push-dnsmasq "dnsmasq-adblock-update-hosts $(date -Iseconds)"
